baseURL = 'https://mustardseed.eone.one/'
relativeURLs = true

languageCode = 'ko'
#languageCode = 'en-us'
title = '겨자씨'
theme = "mainroad"

# Number of posts per page
# paginate = 5
pagination.pagerSize = 5
copyright = "&copy;{year}, All Rights Reserved"
summaryLength = 2

disqusShortname = "gyeojassi" # DEPRECATED! Use .Services.Disqus.Shortname
googleAnalytics = "G-Z320PYZ29Q" # DEPRECATED! Use .Services.googleAnalytics.ID

[services]
  [services.disqus]
    shortname = "gyeojassi" # Enable Disqus by entering your Disqus shortname
  [services.googleAnalytics]
    ID = "G-Z320PYZ29Q" # Enable Google Analytics by entering your tracking ID

enableRobotsTXT = true
enableEmoji = true

[permalinks]
  post = '/:section/:year/:yearday/:slug/'
  page = '/:section/:slug/'

[Params]
  # Description of your site
  description = "믿음을 가지세요" 
  copyright = "eOne" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true
  # Set your X/Twitter handle (include @) to enable twitter:site and twitter:creator tags
  twitter_site = "@handsomeJung"
  # Show "Read more" button in list if true
  readmore = false 
  authorbox = false
  comments = true # Enable Disqus comments for specific page
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  # Order of post meta information
  post_meta = ["date", "categories"] 
  mainSections = ["post", "docs"]
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts


[Params.Author]
  name = "야근반장"
  bio = "이직 후 첫날 해야할 일 - 다음 이직 준비"
  avatar = "img/avatar.jpg"

[Params.logo]
  #image = "/img/logo-tree.svg"
  image = "/img/logo.svg"
  title = "겨자씨"
  subtitle = "너희가 만일 믿음이 한 겨자씨만큼만 있으면 ... 너희가 못할 것이 없으리라"

[Params.thumbnail]
  # list, post
  visibility = ["list", "post"]

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order ex) search, ddg-search, recent, categories, taglist, social, languages
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5